package Dashboard::Model::DBIC;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

1;
__END__

=head1 NAME

Dashboard::Model::DBIC - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Dashboard>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Subscriber::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.4

=head1 AUTHOR

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
